language: ruby
rvm:
  - 2.3.1
cache: bundler
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
before_install:
  - gem update --system
  - gem --version
script:
  - bin/rails db:migrate RAILS_ENV=test
  - bin/rails db:seed RAILS_ENV=test
  - bundle exec rspec spec/
addons:
  firefox: "18.0"
